### ISSUE TITLE
Unreadable focus state on header menu items

### ISSUE THREAD

**Issue by mikemonteith** [nhsx/nhsx-website#61]
## Description

The `:focus` state on header menu items produces unreadable grey text on a dark blue background.

## How to replicate

1. Use the tab key to select a menu item.
2. Menu item is unreadable.

![image](https://user-images.githubusercontent.com/227467/87594467-ebda0b00-c6e4-11ea-9e3e-0065a8b0d450.png)

**Comment by chrimesdev** [comment]
The `:hover :active` state is also unreadable, as seen on the Blogs navigation item blow:

<img width="1136" alt="Screenshot 2021-01-20 at 14 27 21" src="https://user-images.githubusercontent.com/11615501/105188266-9e26db00-5b2b-11eb-83cb-bf841baa860b.png">

**Comment by dragondave** [comment]
Hmmm. I'm struggling to reproduce this. I'm clicking on the space between the NHSX logo and the search bar, pressing the TAB key a few times to highlight 'Blog' in yellow then moving the mouse over it but not clicking, and it remains in yellow for me.
I've tested Firefox 87 and Chrome 89/90 and not seen the issue.

Is that what you're doing, or is there something else I'm missing?
Can you currently reproduce it? It's possible it's been fixed in the meantime.

**Comment by chrimesdev** [comment]
Hi @dragondave seems OK on my end now, looks like it was fixed in https://github.com/nhsx/nhsx-website/pull/164

**Comment by dragondave** [comment]
Thank you!
